### ISSUE TITLE
Re-organize code

### ISSUE THREAD

**Issue by larssono** [Sage-Bionetworks/synapsegraphdb#18]
Currently there is a lot of mixing between Synapse communication, graph building and NEO4j import.  Ideally these operations would be abstracted from each other so that it would be possible to communicate with Synapse without building the graph and populating the graph db seperately.

I suggest 
- [x]  Move all Synapse communication to one location that dumps a representation to file(s)
- [x] Remove the two very similar command line interfaces (activities2Graph.py and convertSynapse2Graph.py and make a single interface.
- [x] Use these files to build up the graph (currently by separating batch fetching by project causes issues with linking between entities in different projects.
- [x] Move all NEO4j interaction to separate code that uses output from built graph.

**Comment by kdaily** [comment]
I'll take a look at NEO4j interaction steps - related to #17.

**Comment by kdaily** [comment]
activites2graph is the main entry - creates a json file. separate script to split this into node and edge csv files, and separate script to split this by entity and edge type for batch import to neo4j.
