### ISSUE TITLE
README improvements

### ISSUE THREAD

**Issue by kdaily** [Sage-Bionetworks/synapsegraphdb#3]
Needs more work.
- [x] Short paragraph right after title describing what it is
- [x] Introduction - describes what problem it solves
- [x] How to install and dependencies (DB, Python libs, Amazon resources, etc)
- [x] How to run (what do each of the scripts do)
- [x] How to use (the current use cases (e.g. PEC, PCBC, etc); example queries with descriptions what they do)
- [x] What still needs to be implemented (possibly open some GH Issues)
- [x] How to contribute (what do I do to change something or make an improvement?)
- [x] Format all 'example queries' in code blocks (using `backticks`)

**Comment by kdaily** [comment]
Looking better on readme, thanks! Still some things to address:

- [ ] info on EC2 and other Amazon resources used
- [ ] move up contact info
- [ ] move example queries out of main readme into a separate Markdown file, maybe in sub-folder of 'examples'

**Comment by kdaily** [comment]
See #4 for a start - merge more changes into this branch please!

**Comment by kendama** [comment]
Tentatively addressed
