### ISSUE TITLE
Help/contact at neo4j

### ISSUE THREAD

**Issue by kdaily** [Sage-Bionetworks/synapsegraphdb#7]
@kendama - who did you have as a contact at neo4j?

**Comment by kendama** [comment]
I believe his name was Alex Price, but I do not have email address, as I was using my Sage email to contact him and I no longer have access to that. If you can't find his contact information through a simple search, I would try contacting their support team through the website and maybe mention his name if you specifically wanted help from him.

**Comment by kdaily** [comment]
Thanks!
